name: Publish Python distributions to PyPI and TestPyPI

on:
  workflow_dispatch:

jobs:
  python-build-n-publish:
    name: Build and publish Python distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Initialize Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Build binary wheel and a source tarball
        run: python setup.py sdist

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: pypi-AgEIcHlwaS5vcmcCJDc3NzM5YzA3LWQwY2QtNDc2OS1hOGYxLTkxYTc5MDQ1ZWRlNAACKlszLCIyYWQ1YTE1MS1jZTQwLTQwZDYtYjhkZS01NWJlZTZiZWJlMjIiXQAABiBxxwo5QZsSnqksYPKJEiPLFniA2wg741Quv83QpdtyEA
          repository_url: https://upload.pypi.org/legacy/